### ISSUE TITLE
Crash to desktop when trying to place suncollector into 2x2 crafting grid.

### ISSUE THREAD

**Issue by pactuslupus** [RacerDelux/MagicalPotionsAndBrews#4]
[crash-2016-07-12_00.25.31-client.txt](https://github.com/RacerDelux/MagicalPotionsAndBrews/files/358556/crash-2016-07-12_00.25.31-client.txt)

**Comment by RacerDelux** [comment]
Thank you for the crash. Fix in version 0.1.6.
